apiVersion: v1
kind: ConfigMap
metadata:
  name: course-app-config-map
data:
  HELLO_MESSAGE: "Hello, it's homework from Kyrylo Meretskyi!"
  APP_STORE: redis
  APP_REDIS_URL: redis://dragonfly.dragonfly-operator-system.svc.cluster.local:6379
